name: Mobile Verifier Manual-Trigger-Build

on: workflow_dispatch

jobs:
  build-maven-mobile-verifier:
    uses: iiitb-pilot/kattu/.github/workflows/maven-build.yml@master
    with:
      SERVICE_LOCATION: ./mobile-verifier
      BUILD_ARTIFACT: mobile-verifier
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers:
    needs: build-maven-mobile-verifier
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'mobile-verifier'
            SERVICE_NAME: 'mobile-verifier'
            BUILD_ARTIFACT: 'mobile-verifier'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: iiitb-pilot/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      BUILD_ARTIFACT: ${{ matrix.BUILD_ARTIFACT }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
